sonar.projectKey=Rida-thedeveloper_Electricity-Billing-System
sonar.organization=rida-thedeveloper

# Optional but recommended:
sonar.projectName=Electricity-Billing-System
sonar.projectVersion=1.0

# Path to your source code folder
sonar.sources=./electricity/billing/system

# Encoding
sonar.sourceEncoding=UTF-8
