sonar.projectKey=Rida-thedeveloper_Electricity-Billing-System
sonar.organization=rida-thedeveloper
sonar.projectName=Electricity-Billing-System
sonar.language=java
sonar.sources=.
# Ye line important hai ↓
sonar.java.binaries=.
# Agar abhi compile nahi karti, to ye line add karo ↓
sonar.exclusions=**/*.class
